# Generated by Django 5.2.5 on 2025-08-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='county_symbols/')),
                ('description', models.TextField(blank=True, help_text='Brief info about the county', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_gallery/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='party_symbols/')),
                ('Leader', models.CharField(max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField(blank=True, default=0, null=True)),
                ('area_km2', models.FloatField(blank=True, default=0.0, null=True)),
                ('number_of_wards', models.IntegerField(blank=True, default=0, null=True)),
                ('current_mp', models.CharField(blank=True, max_length=100)),
                ('voter_turnout', models.FloatField(blank=True, default=0.0, help_text='Latest election voter turnout in %', null=True)),
                ('development_index', models.FloatField(blank=True, default=0.0, help_text='Out of 100', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='symbols/constituencies/')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='core.county')),
            ],
            options={
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('position', models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('mp', 'Member of Parliament')], max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('manifesto', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.constituency')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_gallery/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.candidate')),
            ],
        ),
    ]
