# Generated by Django 5.2.5 on 2025-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='area_km2',
            field=models.CharField(blank=True, help_text='Area in square kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
