# Generated by Django 5.2.5 on 2025-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_county_area_km2_alter_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='population',
            field=models.CharField(blank=True, null=True),
        ),
    ]
