# Generated by Django 5.2.5 on 2025-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_county_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='area_km2',
            field=models.CharField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='population',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
