# Generated by Django 5.2.5 on 2025-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_constituency_area_km2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='current_gov',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='county',
            name='no_of_constituencies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
