# Generated by Django 5.2.5 on 2025-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_county_current_gov_county_no_of_constituencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_incumbent',
            field=models.BooleanField(default=False),
        ),
    ]
